/* ═══════════════════════════════════════════════════════════════
   Pixel icons, drawn on a 12×12 grid ("X" = lit pixel) and rendered as
   crisp SVG rects in currentColor. One set for every theme: they read as
   Nintendo-handheld pixels in the DS / Game Boy styles and as tidy
   glyphs in the Switch style.
   ═══════════════════════════════════════════════════════════════ */
const MAPS = {
  home: `
XXXXX..XXXXX
XXXXX..XXXXX
XXXXX..XXXXX
XXXXX..XXXXX
XXXXX..XXXXX
............
............
XXXXX..XXXXX
XXXXX..XXXXX
XXXXX..XXXXX
XXXXX..XXXXX
XXXXX..XXXXX`,
  swords: `
X..........X
XX........XX
.XX......XX.
..XX....XX..
...XX..XX...
....XXXX....
....XXXX....
...XX..XX...
.XXX....XXX.
.XX......XX.
X..X....X..X
............`,
  plan: `
...XXXXXX...
.XXX....XXX.
.X.XXXXXX.X.
.X........X.
.X.XX.XXX.X.
.X........X.
.X.XX.XXX.X.
.X........X.
.X.XX.XXX.X.
.X........X.
.XXXXXXXXXX.
............`,
  roster: `
XX.XX.XX.XX.
XX.XX.XX.XX.
............
XX.XX.XX.XX.
XX.XX.XX.XX.
............
XX.XX.XX.XX.
XX.XX.XX.XX.
............
XX.XX.XX.XX.
XX.XX.XX.XX.
............`,
  users: `
...XXX......
..XXXXX.XX..
..XXXXXXXXX.
..XXXXX.XX..
...XXX..XX..
............
.XXXXXXX.XX.
XXXXXXXXXXXX
XXXXXXXXXXXX
XXXXXXXXXXXX
............
............`,
  shield: `
.XXXXXXXXXX.
.XXXXXXXXXX.
.XXX....XXX.
.XXX....XXX.
.XXXXXXXXXX.
.XXXXXXXXXX.
..XXXXXXXX..
..XXXXXXXX..
...XXXXXX...
....XXXX....
.....XX.....
............`,
  gear: `
....X..X....
..XXXXXXXX..
.XXXXXXXXXX.
.XXX....XXX.
XXX......XXX
.XX......XX.
.XX......XX.
XXX......XXX
.XXX....XXX.
.XXXXXXXXXX.
..XXXXXXXX..
....X..X....`,
  trophy: `
............
.XXXXXXXXXX.
XX.XXXXXX.XX
XX.XXXXXX.XX
.X.XXXXXX.X.
..XXXXXXXX..
...XXXXXX...
.....XX.....
.....XX.....
....XXXX....
...XXXXXX...
............`,
  flag: `
............
.XXXXXXX....
.XXXXXXXXX..
.XXXXXXXXXX.
.XXXXXXXXX..
.XXXXXXX....
.X..........
.X..........
.X..........
.X..........
.X..........
............`,
  ticket: `
............
............
XXXXXXXXXXXX
XXXXXXX.XXXX
XXXXXXXXXXXX
.XXXXXX.XXX.
.XXXXXXXXXX.
XXXXXXX.XXXX
XXXXXXXXXXXX
XXXXXXX.XXXX
............
............`,
  gym: `
.....XX.....
....XXXX....
...XXXXXX...
..XXXXXXXX..
.XXXXXXXXXX.
XXXXXXXXXXXX
.X........X.
.X.XX..XX.X.
.X.XX..XX.X.
.X........X.
.XXXXXXXXXX.
............`,
  calendar: `
..X.....X...
.XXXXXXXXXX.
.XXXXXXXXXX.
.X........X.
.X.XX.XX..X.
.X........X.
.X.XX.XX..X.
.X........X.
.XXXXXXXXXX.
............`,
  edit: `
.........XX.
........XXXX
.......XXXX.
......XXXX..
.....XXXX...
....XXXX....
...XXXX.....
..XXXX......
.XXXX.......
.XXX........
XXX.........
XX..........`,
  bolt: `
......XXX...
.....XXX....
....XXX.....
...XXX......
..XXXXXXXX..
.......XXX..
......XXX...
.....XXX....
....XXX.....
...XX.......
..X.........
............`,
  search: `
..XXXX......
.X....X.....
X......X....
X......X....
X......X....
X......X....
.X....X.....
..XXXXXX....
.......XX...
........XX..
.........XX.
..........X.`,
  lock: `
....XXXX....
...X....X...
...X....X...
...X....X...
..XXXXXXXX..
..XXXXXXXX..
..XXX..XXX..
..XXX..XXX..
..XXXXXXXX..
..XXXXXXXX..
............
............`,
  unlock: `
....XXXX....
...X....X...
...X........
...X........
..XXXXXXXX..
..XXXXXXXX..
..XXX..XXX..
..XXX..XXX..
..XXXXXXXX..
..XXXXXXXX..
............
............`,
  note: `
.XXXXXXX....
.X.....XX...
.X.XXX.X.X..
.X.....XXXX.
.X.XXXXXX.X.
.X........X.
.X.XXXXXX.X.
.X........X.
.X.XXXX...X.
.X........X.
.XXXXXXXXXX.
............`,
  check: `
............
............
..........XX
.........XX.
........XX..
XX.....XX...
.XX...XX....
..XX.XX.....
...XXX......
....X.......
............
............`,
  x: `
............
.XX......XX.
..XX....XX..
...XX..XX...
....XXXX....
.....XX.....
....XXXX....
...XX..XX...
..XX....XX..
.XX......XX.
............
............`,
  star: `
.....XX.....
.....XX.....
....XXXX....
XXXXXXXXXXXX
.XXXXXXXXXX.
..XXXXXXXX..
...XXXXXX...
...XXXXXX...
..XXX..XXX..
..XX....XX..
.XX......XX.
............`,
  sun: `
.....XX.....
.X...XX...X.
..X......X..
....XXXX....
...XXXXXX...
XX.XXXXXX.XX
XX.XXXXXX.XX
...XXXXXX...
....XXXX....
..X......X..
.X...XX...X.
.....XX.....`,
  moon: `
....XXXX....
..XXX.......
.XXX........
.XX.........
XXX.........
XXX.........
XXX.........
XXXX......X.
.XXXX....XX.
..XXXXXXXX..
....XXXX....
............`,
  plus: `
............
.....XX.....
.....XX.....
.....XX.....
.....XX.....
.XXXXXXXXXX.
.XXXXXXXXXX.
.....XX.....
.....XX.....
.....XX.....
.....XX.....
............`,
  out: `
XXXXXX......
X...........
X.......X...
X.......XX..
X...XXXXXXX.
X...XXXXXXX.
X.......XX..
X.......X...
X...........
XXXXXX......
............
............`,
};

// Merge each row's runs of lit pixels into one rect
const SVG = {};
for (const [name, map] of Object.entries(MAPS)) {
  const rows = map.trim().split('\n');
  const w = Math.max(...rows.map(r => r.length));
  let rects = '';
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length;) {
      if (row[x] !== 'X') { x++; continue; }
      let e = x;
      while (row[e] === 'X') e++;
      rects += `<rect x="${x}" y="${y}" width="${e - x}" height="1"/>`;
      x = e;
    }
  });
  SVG[name] = `<svg class="ico" viewBox="0 0 ${w} ${rows.length}" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true">${rects}</svg>`;
}
export const ico = name => SVG[name] || '';
